### PR TITLE
Removed recursive row class, so it doesn't exceed horizontal viewport

### PR DESCRIPTION
**Pull request by naidraikzir**

### CODE REVIEW

**Comment by arschles** [comment]
Deploy preview processing.

Built with commit f6acc06d2e36d261214fb8afb6bc1f51bd0e7dd5

https://app.netlify.com/sites/goin5minutes/deploys/591b3140a700c454572e6f67

**Comment by arschles** [comment]
Hi @naidraikzir - can you post a screenshot in here with an example of the problem that this fixes?

**Comment by naidraikzir** [comment]
row class gives negative margins to sides, so it exceeds the viewport if you don't use col-* class inside it:
screen shot 2018-01-16 at 21 38 18

Fix:
screen shot 2018-01-16 at 21 39 59

This is just making it equal width to the content underneath it:
screen shot 2018-01-16 at 21 45 17
screen shot 2018-01-16 at 21 56 01

**Comment by arschles** [comment]
@naidraikzir thanks so much for the screenshots. can you resolve conflicts and then ping me so I can merge?

**Comment by arschles** [comment]
Thank you @naidraikzir - merging now!

**Pull request merged**
