### PR TITLE
add redis database interface to the episode0

### PR DESCRIPTION
**Pull request by casertap**
Following your example I decided to create a redis client wrapper that will implement the HashTable interface.
So this wrapper could be the one used in production and the InMemoryHashtable the one used in tests.

You need to install the package: 'gopkg.in/redis.v3' and have an instance of redis-server running to pass the redis_database_test.go test.
Thus, using a mock instead decouples your tests from your infrastructure while having your business logic tested properly.

### CODE REVIEW

**Comment by arschles** [comment]
@casertap thanks for this (and sorry for the delay)! Just a note - I didn't make this very clear in episode 0, but https://godoc.org/github.com/hoisie/redis already adheres to the interface I presented.

Anyway, can you add some Godoc compatible documentation to redis_database.go and also a few comments in `redis_database_test.go` on how to pass the tests (i.e. that you need a redis server running)?

**Comment by casertap** [comment]
Hi @arschles, I have added the comments.

**Comment by arschles** [comment]
@casertap cool, thanks. now I see that the file modes of a bunch of files have changed. is that intentional?

**Comment by casertap** [comment]
Damn, I decided to fetch your new episode into my fork version. All the changes I got by doing the merge are reflected in this push request. I think it is not a big deal because I did not change any file of your new episodes. I plan to watch them tomorrow.

**Comment by arschles** [comment]
@casertap it looks like you changed a lot of files in episode 0 and 1, and also the .gitignore. Can you change the permissions back before I merge?

**Comment by casertap** [comment]
What a mess! sorry about that. I switch back all the permissions.
Next time, when I update my fork version I will use the github https address and not the git address to keep all the permissions identical.

**Comment by arschles** [comment]
no problem at all @casertap - I'm looking forward to getting your code into the repo! ping me when it's all ready

**Comment by casertap** [comment]
Ok Thanks, I think it is good. the commit 4bc229b has solved all the permissions problems.

**Comment by arschles** [comment]
perfect, thanks @casertap. also, I'd love it if you could spread the word on this screencast!

**Pull request merged**
